In [1]:
import numpy as np

In [2]:
x = np.float32(1.0)
x

1.0

In [3]:
y = np.int_([1,2,4])
y

array([1, 2, 4])

In [4]:
z = np.arange(3,dtype=np.uint8)
z

array([0, 1, 2], dtype=uint8)

In [5]:
z.dtype

dtype('uint8')

In [6]:
x = np.array([2,3,1,0])
x

array([2, 3, 1, 0])

In [7]:
x = np.array([2, 3, 1, 0])
x

array([2, 3, 1, 0])

In [8]:
print('Dimensions: ',x.ndim)

Dimensions:  1


In [9]:
print('Data type: ', x.dtype)

Data type:  int64


In [10]:
print('Shape: ',x.shape)

Shape:  (4,)


In [11]:
print('Size: ',x.size)

Size:  4


In [12]:
print('Item size: ',x.itemsize)

Item size:  8


In [13]:
x = x.reshape(1,x.shape[0])
x.shape

(1, 4)

In [14]:
x

array([[2, 3, 1, 0]])

In [15]:
x[0,2] = 25  # first row, second column

In [16]:
x

array([[ 2,  3, 25,  0]])

In [17]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [18]:
x[0,1]

(2+0j)

In [19]:
x.shape

(3, 2)

In [20]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.linspace(1.,4.,6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [23]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
x[0]

array([0, 1, 2, 3, 4])

In [26]:
y = np.zeros((3,4))
y

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [27]:
z = np.ones((4,5))
z

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [28]:
p = np.full((3,3),5)
p

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [29]:
q = np.eye(5,5)
q

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
r = np.random.random((3,3))
r

array([[0.64188591, 0.39623544, 0.55725562],
       [0.69074054, 0.13271208, 0.510593  ],
       [0.07868643, 0.98333428, 0.81795355]])

In [31]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [33]:
a[:10:2]

array([0, 2, 4, 6, 8])

In [34]:
a[::3]

array([0, 3, 6, 9])

In [35]:
a[2::3]

array([2, 5, 8])

In [36]:
a[5:]=20
a

array([ 0,  1,  2,  3,  4, 20, 20, 20, 20, 20])

In [37]:
y = np.arange(5)
y

array([0, 1, 2, 3, 4])

In [38]:
a[5:] = y[::-1]
a

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

In [39]:
x = np.arange(35).reshape(5,7)
x

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [40]:
x[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])